spring.application.name=fluxo

# Configuração da Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fluxo_db
spring.datasource.username=docker
spring.datasource.password=123456

# Driver do PostgreSQL (geralmente o Spring Boot já infere isso, mas é bom garantir)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (muito comum em projetos Spring)
# 'update': permite que o Hibernate crie ou atualize as tabelas no banco 
# a partir das suas classes @Entity. Ótimo para desenvolvimento.
spring.jpa.hibernate.ddl-auto=update

# Define um usuário e senha fixos para o Spring Security em desenvolvimento
spring.security.user.name=admin
spring.security.user.password=1234
